name: Pipeline

run-name: 🗿🗿 Run triggered by ${{ github.actor }} 🗿🗿
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: /home/actions-runner/dotnet
    steps:
      - name: Check 🗿 out 🗿 repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9
      - name: Build 🗿 projects
        run: |
          dotnet build Deo.Backend
          dotnet build Deo.Frontend
      - name: Upload 🗿 artifacts
        uses: actions/upload-artifact@v5
        with:
          name: build
          path: |
            **/bin/
            **/obj/